version: "3.3"

services:
  traefik:
    image: "traefik"
    command:
      - "--global.sendAnonymousUsage=false"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.traefik.address=:8080"
      - "--log.level=WARN"
      - "--certificatesResolvers.le.acme.email=stephen@madsportslab.com"
      - "--certificatesResolvers.le.acme.storage=acme.json"
      - "--certificatesResolvers.le.acme.tlsChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"
    labels:
      - "traefik.http.routers.http_catchall.rule=HostRegexp(`{any:.+}`)"
      - "traefik.http.routers.http_catchall.entrypoints=web"
      - "traefik.http.routers.http_catchall.middlewares=https_redirect"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"

    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
  redis:
    image: "redis"
    restart: "unless-stopped"
    volumes:
      - "redata:/data"
  nbad:
    image: "nbad"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nbad.rule=Host(`madsportslab.pro`) && PathPrefix(`/`, `/api`, `/games`, `/teams`, `/players`, `/live`, `/downloads`)"
      - "traefik.http.routers.nbad.entrypoints=web"
      - "traefik.http.routers.nbad.tls=true"
      - "traefik.http.routers.nbad.tls.certresolver=le"
      - "traefik.http.middlewares.nbad.compress=true"
    restart: "unless-stopped"
    volumes:
      - "./secrets:/run/secrets"
    depends_on:
      - "redis"
volumes:
  redata: {}
