version: "3.3"

services:
  traefik:
    image: "traefik"
    command:
      - "--global.sendAnonymousUsage=false"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.traefik.address=:8080"
      - "--log.level=WARN"
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: "redis"
    restart: "unless-stopped"
    volumes:
      - "redata:/data"
  nbaddev:
    image: "nbaddev"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nbaddev.rule=PathPrefix(`/`, `/api`, `/games`, `/teams`, `/players`, `/live`, `/downloads`)"
      - "traefik.http.routers.nbaddev.entrypoints=web"
    restart: "unless-stopped"
    volumes:
      - "./secrets:/run/secrets"
    depends_on:
      - "redis"
volumes:
  redata: {}
